ALTER TABLE dim_store_details
ALTER COLUMN longitude SET DATA TYPE FLOAT USING (longitude::FLOAT),
ALTER COLUMN latitude SET DATA TYPE FLOAT USING (latitude::FLOAT),
ALTER COLUMN locality SET DATA TYPE VARCHAR(20),
ALTER COLUMN store_code SET DATA TYPE VARCHAR(12),
ALTER COLUMN staff_numbers SET DATA TYPE SMALLINT USING (staff_numbers::SMALLINT),
ALTER COLUMN opening_date SET DATA TYPE DATE,
ALTER COLUMN store_type SET DATA TYPE VARCHAR(11),
ALTER COLUMN country_code SET DATA TYPE VARCHAR(2),
ALTER COLUMN continent SET DATA TYPE VARCHAR(7);

