ALTER TABLE dim_users
  ALTER COLUMN first_name SET DATA TYPE VARCHAR,
  ALTER COLUMN last_name SET DATA TYPE VARCHAR,
  ALTER COLUMN date_of_birth SET DATA TYPE DATE,
  ALTER COLUMN country_code SET DATA TYPE VARCHAR,
  ALTER COLUMN user_uuid SET DATA TYPE UUID USING (user_uuid::UUID),
  ALTER COLUMN join_date SET DATA TYPE DATE;