ALTER TABLE orders_table
  ALTER COLUMN date_uuid SET DATA TYPE UUID USING (date_uuid::UUID),
  ALTER COLUMN user_uuid SET DATA TYPE UUID USING (user_uuid::UUID),
  ALTER COLUMN card_number SET DATA TYPE VARCHAR(19),
  ALTER COLUMN store_code SET DATA TYPE VARCHAR(12),
  ALTER COLUMN product_code SET DATA TYPE VARCHAR(11),
  ALTER COLUMN product_quantity SET DATA TYPE SMALLINT USING (product_quantity::SMALLINT);